/**
 * GENERATED once by a throwaway script calling the real model with pawmc's real prompts
 * (single developer persona, 12 calls). To refresh: re-run a similar one-off, or play the
 * scenario through a real pawmc instance and hand-assemble.
 *
 * The offline demo replays this script with no LLM and no backend: visitors pick
 * precomputed message options and read precomputed replies, summaries and topic labels.
 */
import type { DemoScript } from "./script-types"

export const demoScript: DemoScript = {
	"diary": "personal",
	"personas": [
		"I'm thirty-four, a backend developer ten years in, fully remote for the last three. My days are half coding, half meetings and reviews, and they end around six when I close the laptop. Evenings I usually drift back to a side project that has been almost done for two years, and Saturday mornings belong to the farmers market and a long bike ride."
	],
	"runs": [
		{
			"topicName": "Daily Work-Life Routine",
			"topicDescription": "User's weekday schedule as a remote backend developer, closing the laptop around 6pm after half coding and half meetings.",
			"topicSummary": "34-year-old backend developer, 10 years in, fully remote for the last 3. Workday is half coding, half meetings/reviews, ending ~6pm when he closes the laptop upstairs. Evenings go to a side project (\"almost done\" for two years) — he values it and looks forward to it; not a problem to fix. Saturday mornings are reserved for the farmers market and a long bike ride.\n\nCore issue: over the past year, meetings and reviews have crowded out most of his coding, leaving him feeling he built nothing by day's end. He stayed silent about this with his manager for a year.\n\nCommitted next steps (his words): tonight he'll count last week's meeting hours so he brings numbers, not a feeling; at tomorrow's 1:1 he'll tell his manager he wants real coding time back and ask for two protected coding mornings per week.\n\nNot yet confirmed: how he'll frame the ask or any specific handoffs — no response yet on the proposed opener.",
			"topicMicro": "Remote backend dev asking his manager for two protected coding mornings after meetings crowded out his coding time.",
			"categorySummary": "The overall routine is stable and healthy: a fully remote senior backend developer (34, 10 yrs) keeps a consistent workday ending ~6pm, invests evenings in a long-running side project he genuinely values (not a problem to fix), and protects Saturday mornings for the farmers market and a bike ride. The single pressure point is work content: over the past year, meetings and reviews have crowded out coding, leaving him feeling he built nothing by day's end — a frustration he stayed silent about with his manager for a year. The category's current focus is self-advocacy: he committed to tallying last week's meeting hours so he brings numbers, not a feeling, and to asking in tomorrow's 1:1 for two protected coding mornings per week. Open items: final framing of the ask and any handoff specifics; no response yet on the proposed opener.",
			"beat1Reply": "The routine itself sounds solid — hard stop at six, protected Saturday mornings. So the first question: what do you actually want to change, if anything?\n\nThe thing that jumps out is the side project. Two years of \"almost done\" with evenings that *drift* into it reads like it's become neither real work nor real rest. Do you want to finish it, or is it a default habit you'd drop with permission? And if the real issue is something else — energy by evening, the meeting load, the flatness of three years remote — say so and we'll start there instead.",
			"beat2Message": "The project's fine, honestly it's the part of the week I look forward to. What's actually going on is the day job: over the past year the meetings and reviews have crowded out most of the coding, and by six I feel like I didn't build anything all day. That's what I want to figure out.",
			"beat2Reply": "Then this is a calendar and role problem, and the fix depends on which kind of drift it's been.\n\nTwo things to establish first. One: the actual numbers. Count last week — hours in meetings, hours with an editor open. People in your position usually guess, and it's worth knowing whether you're at 30% coding or 10%, because that changes the conversation.\n\nTwo: sort the meetings. Which ones exist because you're the bottleneck — you're the approver, the decider — and which ones survive because nobody ever uninvited you? The first kind needs a delegation conversation. The second kind you can decline or convert to async this week without asking anyone.\n\nWorth saying: some of this load is career capital. Ten years in, being the reviewer is influence, so the goal probably isn't zero meetings — it's coding that's load-bearing again rather than squeezed into gaps.\n\nSo: roughly how many meeting hours, and do they cluster in the mornings or spread out? And has \"I want more hands-on time\" ever actually been said to your manager, or has this stayed silent for the year?",
			"beat3Message": "I've been quiet about this for a year, so here's the commitment: at tomorrow's 1:1 I'm telling my manager I want real coding time back and asking for two protected coding mornings a week. Tonight I'll count last week's meeting hours so I walk in with numbers.",
			"beat3Reply": "Good shape — two mornings is a specific, sayable yes. A few things to make it land.\n\nTonight count two things: total meeting hours, and which of those you were the approver in. The manager's first question will be \"which ones go?\" — walk in with that list, plus who could take them. \"I'll hand the service reviews to X and shadow her for two weeks\" turns the ask into scaling yourself, which is a much easier yes than \"give me my time back.\"\n\nShape it as a proposal, not a grievance. Not \"meetings ate my year\" but: \"Last week was X hours in meetings, Y coding. I want two protected mornings for hands-on work, and here's what I'm handing off to make room.\"\n\nTwo mechanics once you get the yes. Block the mornings recurring tonight, before the 1:1 — a defended slot beats an unbooked one. And set the review point inside the meeting itself: \"let's look at how this is holding in a month.\" Protected time erodes quietly otherwise; a scheduled check makes the erosion visible.",
			"day2Message": "Found an old photo while digging for a charging cable, me at six on a bike way too big for me and dad running behind with his hand out, probably the moment before he let go. Called him on the spot and we talked for an hour, and now I keep thinking I should call him like that more than twice a year.",
			"day2Reply": "Good instinct, and calling on the spot was the right move. But \"more than twice a year\" won't survive busy weeks unless the trigger stops being \"found an old photo while digging for a cable.\" Spontaneity made that call good; it won't make the next four happen. Same lesson as your 1:1 prep — don't wait for the feeling to arrive, build the trigger.\n\nConcrete version: give it a slot, like the farmers market. Saturday morning after the ride, or Sunday evening. Pick a frequency — weekly or every other week — and put a recurring event on the calendar. Short calls count: a standing 20 minutes every week beats two hour-long calls a year.\n\nTwo things that lower the bar and improve the calls: text him the photo if you haven't, and ask him to dig up his old ones — every photo he sends is a future call topic. And keep a running note of things worth telling him, so you open with the saved thing instead of small talk.",
			"topic2Name": "Calling Dad More Often",
			"topic2Description": "User found an old photo of learning to ride a bike with dad, called him for an hour on the spot, and resolved to call more than twice a year."
		}
	]
}
